{% set name = 'monocle' %}
{% set version = '2.4.0' %}

package:
  name: r-{{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url:
    - https://bioconductor.org/packages/release/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz
  md5: fef48c57d5da92fae71cb501d8603cf0

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base
    - r-biobase
    - r-knitr
    - r-ggplot2
    - r-reshape2

  run:
    - r-base
    - r-biobase
    - r-knitr
    - r-ggplot2
    - r-reshape2

test:
  commands:
    - $R -e "library('monocle')"

about:
  home: https://github.com/cole-trapnell-lab/monocle-release
  license: Artistic-2.0
  summary: Monocle performs differential expression and time-series analysis for single-cell expression experiments. 
  license_family: Other
